### ISSUE TITLE
exception error

### ISSUE THREAD

**Issue by mrooney401** [BenBrostoff/draft-kings-fun#14]
him new to python, I'm getting this error 
Traceback (most recent call last):
  File "optimize.py", line 196, in <module>
    rosters.append(run(POSITIONS[args.l], args.l, remove))
  File "optimize.py", line 107, in run
    raise Exception('No solution error')
Exception: No solution error

any advice? much appreciated.

**Comment by BenBrostoff** [comment]
This error happens when there's no solution based on your command line arguments. I'll make sure to handle it more gracefully. What's your command line query look like?

For this week (9/11), I am able to get projected lineups playing the standard contests. See the screenshot below:

![screen shot 2016-09-10 at 3 12 43 pm](https://cloud.githubusercontent.com/assets/6991348/18412935/12409d42-7769-11e6-8236-0a751efd20a6.png)

**Comment by BenBrostoff** [comment]
I think c62511f5566a0c95e79ae851a53415f393963929 addresses this one; closing this issue.
