### ISSUE TITLE
Documentation and CLI

### ISSUE THREAD

**Issue by audiolion** [BenBrostoff/draft-kings-fun#22]
Hey man!

This is an awesome gem that I came across when I was looking to start working on something similar. I went through the entire codebase, ran different parts of it, stepped through some debug traces and such primarily to figure out how it worked. From the perspective of someone who knows nothing going through the README I think I can offer some edits and help to make it more clear how the library works, what data it pulls, command line options and examples.

Let me know if you are interested and I will submit a PR.

---
Other thoughts on data sources for projections:
I also want to try merging player data projections from all three sources and running the solver, I am thinking we can use edit distance and comparable fantasy point projection margins to match players with slightly different name spellings, otherwise we can use team/position data to match them. I also thought about including expert rankings consensus or other data sources. We could also backtest projections for the year and see which source has the most accurate fantasy projections and when we average the results together give the most accurate sources a weighted average that favors them more.

**Comment by BenBrostoff** [comment]
@audiolion Help would be greatly appreciated, and definitely submit a PR! The README clearly is outdated (Brian Hoyer as Texans QB example 1A) and also doesn't document some of the flags I use every week (`--banned`, `--teams`, etc.).

I like your ideas on projections. I've struggled to find good historical data outside of the NFL's official fantasy API, so that's been a little of a limiting factor. If we had good data going back a few years I'd be excited to try a lot of what you described.

As you pointed out, there's a lot of hackery with different name spellings  in this project that I'd like to clean up. Don't have many good ideas at this point so help definitely needed here.

Anyways, feel free to contribute as much as you want. The better this repo is, the less money DraftKings takes from us every Sunday :-).

**Comment by audiolion** [comment]
haha agree with you there, ok this weekend I will poke around a bit and see what I can do
