### ISSUE TITLE
Mismatched Names

### ISSUE THREAD

**Issue by cabish** [BenBrostoff/draft-kings-fun#55]
~/draft-kings-fun/data$ grep Todd *
current-projections.csv:Todd Gurley LAR ,17.59
current-salaries.csv:RB,Todd Gurley II,6000,IND@LAR 04:05PM ET,12.450,LAR

**Comment by BenBrostoff** [comment]
Alright @cabish , this should work now via 3f3f1c18f61f452917d62b0584603c5519ca92b9. Note that I decided to make the DraftKings naming scheme the single source of truth, so any data scraped through the library will now use these names. If you decide to use your own projections, you will need to use the DraftKings names.

Previously, I was transforming the DraftKings data through `scripts/prepare_nfl_contest_data.sh`; this is no longer happening, so I would recommend downloading the CSV again and running the script.

Closing this issue since this is now fixed I think (see screenshot below). If there any any more naming issues, feel free to submit a PR changing the dictionary in `nfl/data_cleaning_constants.py`.

![screen shot 2017-09-09 at 5 22 45 pm](https://user-images.githubusercontent.com/6991348/30244062-4a4d2fae-9584-11e7-9f6e-7fd424baf307.png)
