### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by karbica** [BenBrostoff/draft-kings-fun#6]
Thanks for this repo, it has potential. I thought about using another Python constraint library to do the same thing but I thought I'd play with this one.

First off, you should consider using Buildout so that the dependencies are met. I had to get three modules before I could get to this point.

<img width="962" alt="screen shot 2015-10-28 at 1 24 20 am" src="https://cloud.githubusercontent.com/assets/8563742/10783173/f7f24bc6-7d12-11e5-8f8a-8629439274d4.png">

Have you gotten this issue before? And are you using virtualenv by any chance?

Much appreciated Ben!

**Comment by BenBrostoff** [comment]
Thanks Kevin - I agree with all these comments. Regarding the error you're getting - the issue here is that you don't have the DraftKings data necessary to run the script. I've updated the <code> README.md </code> with additions on setup here - <a href="https://github.com/BenBrostoff/draft-kings-fun/commit/4519097dc18aabb1c4a43a2a00bba36296904882" target="_blank"> please see this commit </a>. Let me know if this works for you - I included a screenshot of Week 8's projections after following the instructions myself.

Setting up a <code> virtualenv </code> is definitely best practice here, and I apologize for having manually installed the dependencies. What makes using <code> virtualenv </code> a bit difficult is <code> ortools </code> installation was pretty annoying at least for me, and I'd have to look into how to automate it. 

I'd love your help on this repo if you have additional ideas. 

![screen shot 2015-10-28 at 7 49 48 am](https://cloud.githubusercontent.com/assets/6991348/10787600/954978e2-7d48-11e5-98d5-56723bf46688.png)

**Comment by djbrooks111** [comment]
I am too getting the "list index out of range" as @karbica, however, the rosters are still outputted correctly.  My system is setup properly following your instructions, I am on my work computer right now, and so if it would help, when I get home, I can upload my .csv files in /data

**Comment by BenBrostoff** [comment]
@djbrooks111 @karbica I should note too this output is a little deceiving and it should probably be squashed or the parsing should be improved (there's not an issue in the scraping, it's just the structure of the HTML from FanPros). I will work on a change so others don't encounter this problem.

**Comment by BenBrostoff** [comment]
@djbrooks111 @karbica This commit should resolve the aforementioned scraping issues:  c335ab20ad1fcdb7b01578add1d7409b7739cff8. I'll close this issue unless this still isn't working for either of you - here's a screenshot of running the script for this week's Millionaire Maker:

![screen shot 2015-11-30 at 7 31 30 pm](https://cloud.githubusercontent.com/assets/6991348/11488968/fdea2530-9798-11e5-9b66-bb51c8ced777.png)
