### ISSUE TITLE
Support player pools

### ISSUE THREAD

**Issue by BenBrostoff** [BenBrostoff/draft-kings-fun#82]
The idea here would be to be able to pass the optimizer a subset of the slate and have these be the only players the optimizer can choose from.

The next part here (which would be substantially more difficult) would be to allow passing a pool and maximum exposures as a CSV that looks something like this:

```
name, exposure
Player A, 0.90
Player B, 0.35
Player C, 0.5
```

Any player with a percentage not specified would be assumed to be allowed to be 100% of lineups, and at minimum would need to be in at least 1%.

**Comment by BenBrostoff** [comment]
After discussing, this would be:

```
name, min_exposure, max_exposure
Player A, 0.1, 0.3
```

**Comment by sharkiteuthis** [comment]
I made [a branch](https://github.com/sharkiteuthis/draft-kings-fun/tree/exposure-limits) that builds on yours -- instead of locking players in deterministically, it uses `random.random` to decide when to enforce a lock while still respecting the maximum exposure. That way if you have a lot of exposure constraints, they aren't all forced into the first lineups generated.

I'm thinking of my use case here because I tend to start with a smallish player pool (2-4 QB, 10 pricey skill players, ~30 cheaper skill players) and then use exposure limits to mix those up over 100-150 lineups.

It's still not great, because if I want 5-10% Nick Mullens and >35% Lamar Jackson and `random.random()` spits out <0.35, it will try to lock both. That could be fixed by e.g. taking Mullens for `r<=0.1` and Jackson for `r>0.1 and r<=0.45`, but then you have to enforce `sum(mins) <= 1`.

It would also be nice to have group constraints. E.g. I want at least 10% each of MG3, CMC, Saquon, DJ, Chubb and I want each lineup to have at least 2 of those 5.

**Comment by BenBrostoff** [comment]
@sharkiteuthis I think the deterministic and random approach are both valuable and we should have flags where the user can choose either. The group constraints I agree would be awesome but let's handle that in a separate issue.

Let me get my branch merged in first and then you can PR onto `develop`.

**Comment by sharkiteuthis** [comment]
I'll leave keep the deterministic approach and add flags (`-random_exposure` and `-random_exposure_seed`?) for my approach when I put in the PR.

**Comment by BenBrostoff** [comment]
👍 , those flag names are good by me.

**Comment by sharkiteuthis** [comment]
I also added an exposure table::
![image](https://user-images.githubusercontent.com/7672689/48957398-66f61880-ef26-11e8-8a44-015982527c84.png)
